[package]
name = "rfs-utils"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
chrono = "0.4.41"
once_cell = "1.21.3"
termcolor = "1.4.1"
serde = { version = "1", features = ["derive"] }